/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);
    ShellEnv env = ShellEnv.getInstance();

    while (env.isRunning()) {
      String curr = System.getProperty("user.dir");
      System.out.printf("[%s]: ", curr);
      String input = scan.nextLine();
      if (input.length() > 0) {
        env.executeCmd(input);
      }
    }
    scan.close();
  }
}
